name: ci
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
    
    steps:
    - name: ros-workspace
      run: |
        mkdir -p ws/src

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ws/src/traffic_editor

    - name: non-ros-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake wget libyaml-cpp-dev qt5-default libqt5svg5-dev

    - name: build
      shell: bash
      run: |
        cd ws
        source /opt/ros/foxy/setup.bash
        colcon build --packages-select traffic_editor --cmake-args -DNO_DOWNLOAD_MODELS=True

    - name: test
      shell: bash
      run: |
        cd ws
        source /opt/ros/foxy/setup.bash
        QT_QPA_PLATFORM=offscreen colcon test --packages-select traffic_editor

    - name: test-results
      shell: bash
      run: |
        cd ws
        source /opt/ros/foxy/setup.bash
        colcon test-result --verbose
