name: ci_rolling
on: [push]
jobs:
  ci_rolling:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:rolling-ros-base-jammy

    steps:
    - name: ros-workspace
      run: |
        mkdir -p ws/src

    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ws/src/rmf_traffic_editor

    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: open-rmf/rmf_utils
        path: ws/src/rmf_utils

    - name: non-ros-deps
      run: |
        sudo apt-get update
        sudo apt-get install -y git cmake wget libyaml-cpp-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libceres-dev libeigen3-dev python3-shapely python3-requests python3-yaml python3-pyproj python3-fiona python3-rtree libproj-dev

    - name: build
      shell: bash
      run: |
        cd ws
        source /opt/ros/rolling/setup.bash
        colcon build --packages-select rmf_utils
        colcon build --packages-select rmf_traffic_editor --cmake-args -DNO_DOWNLOAD_MODELS=True
        colcon build --packages-up-to rmf_traffic_editor_test_maps --cmake-args -DNO_DOWNLOAD_MODELS=True

    - name: test
      shell: bash
      run: |
        cd ws
        source /opt/ros/rolling/setup.bash
        QT_QPA_PLATFORM=offscreen colcon test --packages-select rmf_traffic_editor

    - name: test-results
      shell: bash
      run: |
        cd ws
        source /opt/ros/rolling/setup.bash
        colcon test-result --verbose
