name: style
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install pycodestyle
    - name: pycodestyle
      run: |
        pycodestyle .
